numbers = [1, 2, 3, 4,5]
numbers.append(5)
numbers.insert(0,7)
numbers.remove(1)
numbers.pop()
print(50 in numbers)
print(numbers.index(5))
print(numbers.count(2))
numbers.sort()
numbers.reverse()
numbers2 = numbers.copy()
numbers2.append(55)
print(numbers)
print(numbers2)
numbers.clear()
